### ISSUE TITLE
Labels for...?

### ISSUE THREAD

**Issue by xDaizu** [bradfrost/single-field-cc#12]
Your example in index.html reads like:

    <form>
			<fieldset class="credit-card-group">
				<legend>Credit Card Information</legend>
				<label for="card-number">Credit Card Number</label>
				<input placeholder="1234 5678 9012 3456" pattern="[0-9]*" type="text" class="card-number" id="card-number">
				<label for="card-number">Expiration Date</label>
				<input placeholder="MM/YY" pattern="[0-9]*" type="text" class="card-expiration" id="card-expiration">
				<label for="card-number">CVV Number</label>
				<input placeholder="CVV" pattern="[0-9]*" type="text" class="card-cvv" id="card-cvv">
				<label for="card-number">Billing Zip Code</label>
				<input placeholder="ZIP" pattern="[0-9]*" type="text" class="card-zip" id="card-zip">
			</fieldset>
	</form>

I couldn't help but noticing that all "for" attributes on every label point to "card number" instead of their respective inputs. Is this a typo or by design?

**Comment by bradfrost** [comment]
@xDaizu Hi there, this project isn't maintained, and in fact, I'm going to archive it now. Check over here for something that's a bit further along: https://github.com/zdfs/toscani

Thanks!
